# Generated by Django 4.2.4 on 2023-10-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='taskDueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='taskPriority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
            preserve_default=False,
        ),
    ]
