# Generated by Django 4.2.4 on 2023-11-01 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_taskmodel_taskduedate_taskmodel_taskpriority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='taskDueDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='todoapp.photo'),
        ),
    ]
