# Generated by Django 4.2.4 on 2023-11-02 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_taskmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskDueDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
